# SPDX-FileCopyrightText: 2025 GabyChangelog <agentepanela2@gmail.com>
# SPDX-FileCopyrightText: 2025 VictorJob <victorjobnogueira12@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: loadout
  id: WeaponPistolMk58Gold
  effects:
    - !type:JobRequirementLoadoutEffect
      requirement:
        !type:DepartmentTimeRequirement
        department: Security
        time: 252000 #70 hrs
  storage:
    back:
    - WeaponPistolMk58Gold
